### ISSUE TITLE
The server could not find the requested resource

### ISSUE THREAD

**Issue by bflorat** [bh90210/dron8s#11]
Can't make it work : 
```
 kubectl create clusterrolebinding dron8s --clusterrole=edit --serviceaccount=default:default --namespace=default
clusterrolebinding.rbac.authorization.k8s.io/dron8s created
```

.drone.yml : 
```
- name: deploy_k8s
  image: bh90210/dron8s:latest
  settings:
    yaml: ./config.yaml 
```

config.yaml : 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
```
Result : 
```
In-cluster SSA initiliazing
Applying config # 0
the server could not find the requested resource
```

Two issues : 
1) the yaml is not applied against the K8S cluster
2) the job failed but Drone sees it as passed

Note: 
Same errors with out of cluster config.

Thx

**Comment by bh90210** [comment]
hello @bflorat just saw it.
thanks for opening the issue! 
let me investigate and I will come back asap :+1:

**Comment by bh90210** [comment]
ok, I have a workaround but a very good explanation of why it is happening in the first place.

but just to make it work: you simply include a `namespace`  and hopefully that should do it.

ie. 
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
  namespace: default
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
```
