### ISSUE TITLE
Restart rollout or update tags of container images

### ISSUE THREAD

**Issue by stv0g** [bh90210/dron8s#12]
How can we restart a rollout of a particular worklload?
I am building Docker images in a previous of our pipeline.
But it seems that we dont have a possibility to update running pods with new images?

**Comment by bh90210** [comment]
Hey Steffen, 

the plugin doesn't provide a way to trigger re-deployment with new image.
There is a drone plugin that does just that but the way I do it is by simply including an env in the config
```yaml
env:
          - name: change
            value: valuevaluevalue
```
and have a step in the pipeline (`.drone.yaml`) to change it so a re-deployment gets triggered.
```yaml
- name: trigger new deployment
  image: golang
  commands: 
  - sed -ie "s/valuevaluevalue/$(date)/g" k8s.yaml

```
