### ISSUE TITLE
Is there a plan to parse variable

### ISSUE THREAD

**Issue by jeessy2** [bh90210/dron8s#14]

**Comment by bh90210** [comment]
hello @jeessy2 can you please be a little more specific as I am not 10/10 sure to what u are referring to?

**Comment by jeessy2** [comment]
like this.

```
kind: pipeline
type: kubernetes
name: dron8s-in-cluster-example
steps:
- name: dron8s
  image: bh90210/dron8s:latest
  settings:
    yaml: ./config.yaml
    # variables. Must be lowercase, Usage: {{.service_name}}
    service_name: myservice
    image_version: 1.8
```

```
apiVersion: v1
kind: Service
metadata:
  name: {{.service_name}}
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: hello-kubernetes
```
