### ISSUE TITLE
Support for kustomize 

### ISSUE THREAD

**Issue by dfoxg** [bh90210/dron8s#29]
Hi there,

i would like to use [Kubernetes kustomize](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/) with this plugin, but currently it fails.

My drone config:
```
- name: static_files_deploy
  image: bh90210/dron8s:latest
  settings:
    yaml: ./k8s/static-files/kustomization.yaml
    kubeconfig:
        from_secret: KUBECONFIG
  when:
    branch:
    - ft/static-files
    event:
      exclude:
      - pull_request
```

my `./k8s/static-files/kustomization.yaml`:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: example-configmap-1
  files:
  - test=./test.html
```

my `test.html`:
```
<!DOCTYPE html>
<html>

<body>
    <h1>Hi!</h1>
</body>

</html>
```

the error in drone:
```
latest: Pulling from bh90210/dron8s
Digest: sha256:c3e0f8b3b78a9ec75cc95fb1619d71b522ee592e6df39c564947ccffd0587bdc
Status: Image is up to date for bh90210/dron8s:latest
Out-of-cluster SSA initiliazing
no matches for kind "Kustomization" in version "kustomize.config.k8s.io/v1beta1"
latest: Pulling from bh90210/dron8s
Digest: sha256:c3e0f8b3b78a9ec75cc95fb1619d71b522ee592e6df39c564947ccffd0587bdc
Status: Image is up to date for bh90210/dron8s:latest
Out-of-cluster SSA initiliazing
no matches for kind "Kustomization" in version "kustomize.config.k8s.io/v1beta1"
```

Thanks!
